#
default: &default
adapter: postgresql
enconding: unicode
development:
<<: *default
database: agendaPersonal_devp
test:
<<: *default
database: agendaPersonal_test
production:
<<: *default
database: agendaPersonal_prod